// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	ID         string  `json:"id"`
	Email      string  `json:"email"`
	GivenName  *string `json:"given_name"`
	FamilyName *string `json:"family_name"`
	MiddleName *string `json:"middle_name"`
}

func (User) IsEntity() {}
